# Meta
title:                      edX Pattern Library
tagline:                    The Visual, UI, and Front End styleguide for edX's applications
url:                        http://code.edx.org/ux-pattern-library
author:
    name:                   edX UX
    url:                    http://www.edx.org
    email:                  ux@edx.org

# Site
baseurl:                    /
permalink:                  /:categories/:title/
relative_permalinks:        true
exampleurl:                 examples/

# Local
exclude:                    ["node_modules", "gulp", "gulpfile.js", "package.json", "bower.json", "pldoc", "pattern-library", "bower_components"]

# Custom vars
github:
    repo:                   https://github.com/edx/ux-pattern-library
    path_scss:              /blob/master/pattern-library/sass/
    docurl:                 https://github.com/edx/ux-pattern-library/wiki/

# Add-ons
ui-toolkit:
    name: edX UI Toolkit
    repo: https://github.com/edx/edx-ui-toolkit
    path_components: /blob/master/components/views/
    docurl: https://github.com/edx/edx-ui-toolkit/blob/master/README.md

# Plugins
highlighter:                pygments

